steps:
  - label: ":jest: Jest Tests"
    command: "npm install && npm test"
    plugins:
      - docker#v3.2.0:
          image: "node:14"
          workdir: /app

  - label: ":eslint: ESLint"
    command: "npm install && npm run lint"
    plugins:
      - docker#v3.2.0:
          image: "node:14"
          workdir: /app

  - label: ":typescript: Build"
    command: "./.buildkite/validate_build.bash"
    plugins:
      - docker#v3.2.0:
          image: "node:14"
          workdir: /app
